version: '3.8'

services:
  avito-shop-service:
    container_name: avito-shop-service
    image: aspnetcoreapp
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [ "/bin/sh", "-c", "dotnet ef database update --project /src/Avito.MerchStore.Infrastructure --startup-project /src/Avito.MerchStore.API && dotnet Avito.MerchStore.API.dll" ]
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=shop;Username=postgres;Password=password
    networks:
      - internal

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d shop'" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal

networks:
  internal: